spring.application.name=Smart-Email-Writer

server.port=8081


#Gimini Api  #GEMINI_API_URL and GEMINI_API_KEY data get from Environment variable
google.api.url=google.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key=

#gimini api_key #GEMINI_API_KEY
google.api.key=${GEMINI_API_KEY}