spring.application.name=Smart-Email-Writer

server.port=8081


#Gimini Api  #GEMINI_API_URL and GEMINI_API_KEY data get from Environment variable

google.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-flash-latest:generateContent
google.api.key=${GEMINI_API_KEY}





#  https://generativelanguage.googleapis.com/v1beta/models/gemini-flash-latest:generateContent

#spring.application.name=Smart-Email-Writer
#server.port=8081
#
## Gemini API
#google.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-flash-latest:generateContent
#google.api.key=${GEMINI_API_KEY}
